# Generated by Django 3.0.8 on 2020-08-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comments_listing_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing_bid',
            field=models.ManyToManyField(to='auctions.Listing'),
        ),
    ]
