# Generated by Django 3.0.8 on 2020-08-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200823_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing_bid',
        ),
    ]
