# Generated by Django 3.0.8 on 2020-08-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200823_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_item',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bidder',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='author',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
