# Generated by Django 3.0.8 on 2020-08-24 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=100000000, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Listing'),
        ),
    ]
